version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - pip install -r requirements.txt
    build:
      - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: conf.py
